/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package chess.util;

/**
 *
 * @author dong
 */
public class Protocol {
    public final static int REQUEST_REGISTER = 10001;
    public final static int REQUEST_LOGIN  = REQUEST_REGISTER + 1; //10002
    public final static int REQUEST_LOGOUT  = REQUEST_LOGIN + 1; //10003
    public final static int REQUEST_NEED_FRIENDS_LIST  = REQUEST_LOGOUT + 1; //10004
    public final static int REQUEST_UPDATE_MAILBOX  = REQUEST_NEED_FRIENDS_LIST + 1; //10005
    public final static int REQUEST_REMOVE_FRIEND = REQUEST_UPDATE_MAILBOX + 1; //10006
    public final static int REQUEST_SEND_MESSAGE = REQUEST_REMOVE_FRIEND + 1; //10007
    public final static int REQUEST_CREATE_ROOM  = REQUEST_SEND_MESSAGE + 1; //10008
    public final static int REQUEST_LIST_ROOMS  = REQUEST_CREATE_ROOM + 1; //10009
    public final static int REQUEST_JOIN_ROOM = REQUEST_LIST_ROOMS + 1; //10010
    public final static int REQUEST_LEFT_ROOM  = REQUEST_JOIN_ROOM + 1; //10011
    public final static int REQUEST_KICK_PLAYER_OUT_ROOM  = REQUEST_LEFT_ROOM + 1; //10012
    public final static int REQUEST_STILL_ONLINE  = REQUEST_KICK_PLAYER_OUT_ROOM + 1; //10013
    public final static int REQUEST_UPDATE_MY_ROOM  = REQUEST_STILL_ONLINE + 1; //10014
    public final static int REQUEST_UPDATE_MY_GAME  = REQUEST_UPDATE_MY_ROOM + 1; //10015
    public final static int REQUEST_NEED_CHANGE_PLAYER  = REQUEST_UPDATE_MY_GAME + 1; //10016
    public final static int REQUEST_ACCEPT_CHANGE_PLAYER  = REQUEST_NEED_CHANGE_PLAYER + 1; //10017
    public final static int REQUEST_REJECTED_CHANGE_PLAYER  = REQUEST_ACCEPT_CHANGE_PLAYER + 1; //10018
    public final static int REQUEST_I_DID_A_MOVE  = REQUEST_REJECTED_CHANGE_PLAYER + 1; //10019
    public final static int REQUEST_DRAW_GAME  = REQUEST_I_DID_A_MOVE + 1; //10020
    public final static int REQUEST_I_AGREE_DRAW_GAME  = REQUEST_DRAW_GAME + 1; //10021
    public final static int REQUEST_I_DENY_DRAW_GAME  = REQUEST_I_AGREE_DRAW_GAME + 1; //10022
    public final static int REQUEST_I_AM_READY  = REQUEST_I_DENY_DRAW_GAME + 1; //10023
    public final static int REQUEST_I_AM_NOT_READY  = REQUEST_I_AM_READY + 1; //10024
    public final static int REQUEST_START_THE_GAME  = REQUEST_I_AM_NOT_READY + 1; //10025
    public final static int REQUEST_SEND_MESSAGE_INROOM = REQUEST_START_THE_GAME + 1; //10026
    
    public final static int RESPONSE_REGISTER_SUCCESSFULLY  = 20001;
    public final static int RESPONSE_REGISTER_FAILURE   = RESPONSE_REGISTER_SUCCESSFULLY + 1; //20002
    public final static int RESPONSE_LOGIN_SUCCESSFULLY   = RESPONSE_REGISTER_FAILURE + 1; //20003
    public final static int RESPONSE_LOGIN_FAILURE   = RESPONSE_LOGIN_SUCCESSFULLY + 1; //20004
    public final static int RESPONSE_LOGOUT_SUCCESSFULLY   = RESPONSE_LOGIN_FAILURE + 1; //20005
    public final static int RESPONSE_LOGOUT_FAILURE  = RESPONSE_LOGOUT_SUCCESSFULLY + 1; //20006
    public final static int RESPONSE_NEW_FRIENDS_LIST  = RESPONSE_LOGOUT_FAILURE + 1; //20007
    public final static int RESPONSE_FRIENDS_QUERY_FAILURE   = RESPONSE_NEW_FRIENDS_LIST + 1; //20008
//    public final static int RESPONSE_REQUEST_MAKE_FRIEND   = RESPONSE_FRIENDS_QUERY_FAILURE + 1; //20009
//    public final static int RESPONSE_ACCEPTED_BE_FRIEND  = RESPONSE_FRIENDS_QUERY_FAILURE + 1; //20010
//    public final static int RESPONSE_REJECTED_BE_FRIEND   = RESPONSE_ACCEPTED_BE_FRIEND + 1; //20011
    public final static int RESPONSE_NEW_MESSAGES   = RESPONSE_FRIENDS_QUERY_FAILURE + 1; //20012
    public final static int RESPONSE_MESSAGES_QUERY_FAILURE   = RESPONSE_NEW_MESSAGES + 1; //20013
    public final static int RESPONSE_ADD_FRIEND_SUCCESSFULLY   = RESPONSE_MESSAGES_QUERY_FAILURE + 1; //20014
    public final static int RESPONSE_ADD_FRIEND_FAILURE   = RESPONSE_ADD_FRIEND_SUCCESSFULLY + 1; //20015
    public final static int RESPONSE_REMOVE_FRIEND_SUCCESSFULLY   = RESPONSE_ADD_FRIEND_FAILURE + 1; //20016
    public final static int RESPONSE_REMOVE_FRIEND_FAILURE   = RESPONSE_REMOVE_FRIEND_SUCCESSFULLY + 1; //20017
    public final static int RESPONSE_SEND_MESSAGE_SUCCESSFULLY   = RESPONSE_REMOVE_FRIEND_FAILURE + 1; //20018
    public final static int RESPONSE_SEND_MESSAGE_FAILURE  = RESPONSE_SEND_MESSAGE_SUCCESSFULLY + 1; //20019
    public final static int RESPONSE_CREATE_ROOM_SUCCESSFULLY   = RESPONSE_SEND_MESSAGE_FAILURE + 1; //20020
    public final static int RESPONSE_CREATE_ROOM_FAILURE   = RESPONSE_CREATE_ROOM_SUCCESSFULLY + 1; //20021
    public final static int RESPONSE_LIST_ROOMS   = RESPONSE_CREATE_ROOM_FAILURE + 1; //20022
    public final static int RESPONSE_LIST_ROOM_FAILURE   = RESPONSE_LIST_ROOMS + 1; //20023
    public final static int RESPONSE_JOIN_ROOM_SUCCESSFULLY   = RESPONSE_LIST_ROOM_FAILURE + 1; //20024
    public final static int RESPONSE_JOIN_ROOM_FAILURE   = RESPONSE_JOIN_ROOM_SUCCESSFULLY + 1; //20024
    public final static int RESPONSE_LEFT_ROOM_SUCCESSFULLY    = RESPONSE_JOIN_ROOM_FAILURE + 1; //20025    
    public final static int RESPONSE_LEFT_ROOM_FAILURE    = RESPONSE_LEFT_ROOM_SUCCESSFULLY + 1; //20026
    public final static int RESPONSE_KICK_PLAYER_OUT_ROOM_SUCCESSFULLY    = RESPONSE_LEFT_ROOM_FAILURE + 1; //20027
    public final static int RESPONSE_KICK_PLAYER_OUT_ROOM_FAILURE    = RESPONSE_KICK_PLAYER_OUT_ROOM_SUCCESSFULLY + 1; //20028
    public final static int RESPONSE_STILL_ONLINE_SUCCESSFULLY    = RESPONSE_KICK_PLAYER_OUT_ROOM_FAILURE + 1; //20029
    public final static int RESPONSE_STILL_ONLINE_FAILURE   = RESPONSE_STILL_ONLINE_SUCCESSFULLY + 1; //20030
    public final static int RESPONSE_INVALID_ROOM   = RESPONSE_STILL_ONLINE_FAILURE + 1; //20031
    public final static int RESPONSE_LIST_MEMBERS    = RESPONSE_INVALID_ROOM + 1; //20032
    public final static int RESPONSE_BE_KICKED   = RESPONSE_LIST_MEMBERS + 1; //20033
    public final static int RESPONSE_GAME_STARTED   = RESPONSE_BE_KICKED + 1; //20034
    public final static int RESPONSE_NEW_MOVES    = RESPONSE_GAME_STARTED + 1; //20035
    public final static int RESPONSE_END_GAME_RESULT   = RESPONSE_NEW_MOVES + 1; //20036
    public final static int RESPONSE_ACCEPTED_DRAW_GAME   = RESPONSE_END_GAME_RESULT + 1; //20037
    public final static int RESPONSE_DENIED_DRAW_GAME   = RESPONSE_ACCEPTED_DRAW_GAME + 1; //20038
    public final static int RESPONSE_NEED_DRAW_GAME   = RESPONSE_DENIED_DRAW_GAME + 1; //20039
    public final static int RESPONSE_PLEASE_DO_A_MOVE   = RESPONSE_NEED_DRAW_GAME + 1; //20040
    public final static int RESPONSE_REQUEST_CHANGE_PLAYER  = RESPONSE_PLEASE_DO_A_MOVE + 1; //20041
    public final static int RESPONSE_ACCEPTED_CHANGE_PLAYER   = RESPONSE_REQUEST_CHANGE_PLAYER + 1; //20045
    public final static int RESPONSE_REJECTED_CHANGE_PLAYER   = RESPONSE_ACCEPTED_CHANGE_PLAYER + 1; //20046
    public final static int RESPONSE_NEED_CHANGE_PLAYER_SUCCESSFULLY    = RESPONSE_REJECTED_CHANGE_PLAYER + 1; //20047
    public final static int RESPONSE_NEED_CHANGE_PLAYER_FAILURE    = RESPONSE_NEED_CHANGE_PLAYER_SUCCESSFULLY + 1; //20048
    public final static int RESPONSE_ACCEPT_CHANGE_PLAYER_SUCCESSFULLY    = RESPONSE_NEED_CHANGE_PLAYER_FAILURE + 1; //20049
    public final static int RESPONSE_ACCEPT_CHANGE_PLAYER_FAILURE = RESPONSE_ACCEPT_CHANGE_PLAYER_SUCCESSFULLY + 1; //20050
    public final static int RESPONSE_REJECTED_CHANGE_PLAYER_SUCCESSFULLY = RESPONSE_ACCEPT_CHANGE_PLAYER_FAILURE + 1; //20051
    public final static int RESPONSE_REJECTED_CHANGE_PLAYER_FAILURE = RESPONSE_REJECTED_CHANGE_PLAYER_SUCCESSFULLY + 1; //20052
    public final static int RESPONSE_I_DID_A_MOVE_SUCCESSFULLY = RESPONSE_REJECTED_CHANGE_PLAYER_FAILURE + 1; //20053
    public final static int RESPONSE_I_DID_A_MOVE_FAILURE = RESPONSE_I_DID_A_MOVE_SUCCESSFULLY + 1; //20054
    public final static int RESPONSE_DRAW_GAME_SUCCESSFULLY = RESPONSE_I_DID_A_MOVE_FAILURE + 1; //20055
    public final static int RESPONSE_DRAW_GAME_FAILURE = RESPONSE_DRAW_GAME_SUCCESSFULLY + 1; //20056
    public final static int RESPONSE_I_AGREE_DRAW_GAME_SUCCESSFULLY = RESPONSE_DRAW_GAME_FAILURE + 1; //20057
    public final static int RESPONSE_I_AGREE_DRAW_GAME_FAILURE = RESPONSE_I_AGREE_DRAW_GAME_SUCCESSFULLY + 1; //20058
    public final static int RESPONSE_I_DENY_DRAW_GAME_SUCCESSFULLY    = RESPONSE_I_AGREE_DRAW_GAME_FAILURE + 1; //20059
    public final static int RESPONSE_I_DENY_DRAW_GAME_FAILURE     = RESPONSE_I_DENY_DRAW_GAME_SUCCESSFULLY + 1; //20060
    public final static int RESPONSE_I_AM_READY_SUCCESSFULLY     = RESPONSE_I_DENY_DRAW_GAME_FAILURE + 1; //20061
    public final static int RESPONSE_I_AM_READY_FAILURE     = RESPONSE_I_AM_READY_SUCCESSFULLY + 1; //20062
    public final static int RESPONSE_I_AM_NOT_READY_SUCCESSFULLY     = RESPONSE_I_AM_READY_FAILURE + 1; //20063
    public final static int RESPONSE_I_AM_NOT_READY_FAILURE      = RESPONSE_I_AM_NOT_READY_SUCCESSFULLY + 1; //20064
    public final static int RESPONSE_START_THE_GAME_SUCCESSFULLY      = RESPONSE_I_AM_NOT_READY_FAILURE + 1; //20065
    public final static int RESPONSE_START_THE_GAME_FAILURE      = RESPONSE_START_THE_GAME_SUCCESSFULLY + 1; //20066    
    public final static int RESPONSE_SEND_MESSAGE_INROM_SUCCESSFULLY = RESPONSE_START_THE_GAME_FAILURE + 1;
    public final static int RESPONSE_SEND_MESSAGE_INROM_FAILURE = RESPONSE_SEND_MESSAGE_INROM_SUCCESSFULLY + 1;
    public final static int RESPONSE_MEMBER_QUERY_FAILURE = RESPONSE_SEND_MESSAGE_INROM_FAILURE + 1;
    public final static int RESPONSE_MOVE_QUERY_FAILURE = RESPONSE_MEMBER_QUERY_FAILURE + 1;
}
